---
- block:
  - name: Add forward entry
    lineinfile:
      path: /var/named/{{ DOMAIN_NAME }}.db
      regexp: '^{{ inventory_hostname | replace("." + DOMAIN_NAME, "") }} IN A {{ hostvars[inventory_hostname]["ansible_env"].SSH_CONNECTION.split(" ")[2] }}'
      line: '{{ inventory_hostname | replace("." + DOMAIN_NAME, "") }} IN A {{ hostvars[inventory_hostname]["ansible_env"].SSH_CONNECTION.split(" ")[2] }}'

  - name: Add reverse entry
    lineinfile:
      path: /var/named/{{ DOMAIN_NAME }}.rev
      regexp: '^{{ hostvars[inventory_hostname]["ansible_env"].SSH_CONNECTION.split(" ")[2].split(".")[3] }} IN PTR {{ hostvars[inventory_hostname]["ansible_facts"]["hostname"] }}.{{ DOMAIN_NAME }}.'
      line: '{{ hostvars[inventory_hostname]["ansible_env"].SSH_CONNECTION.split(" ")[2].split(".")[3] }} IN PTR {{ hostvars[inventory_hostname]["ansible_facts"]["hostname"] }}.{{ DOMAIN_NAME }}.'

  - name: Restart service
    systemd:
      state: restarted
      name: named
  delegate_to: "{{ DNS_INV_NAME }}"
  become: yes
