---
- hosts: names.com
  roles:
    - resolver
  
- hosts: ca.com
  roles:
    - ca

- hosts: webservers, haproxyone.com
  roles:      
    - certificator

- hosts: webservers
  roles:
    - webserver

- hosts: proxies
  roles:
    - proxy

- hosts: webservers, proxies
  roles:
    - trust_ca
