---
- name: Install haproxy
  dnf:
    name:
    - haproxy
    - keepalived
  become: yes
  
- include_tasks: ssl.yml
  with_items: "{{ DOMAINS | default(inventory_hostname) }}"

- import_tasks: haproxy.yml
  
- import_tasks: keepalived.yml
