---
- name: Genreate certificate for master
  block:
    - name: Create a pem file
      shell:
        cmd: cat "{{ SERVER_KEY_LOCATION }}{{ item }}/server.key" "{{ SERVER_CERT_LOCATION }}{{ item }}/server.crt" > /etc/pki/tls/private/{{ item }}/server.pem      

    - name: Fetch pem file
      fetch:
        src: /etc/pki/tls/private/{{ item }}/server.pem
        dest: /tmp/ssl_nodes/{{ MASTER_NAME }}/
        flat: yes
  become: yes
  when: inventory_hostname == MASTER_NAME
 
- name: Copy pem to server
  copy:
    src: /tmp/ssl_nodes/{{ MASTER_NAME }}/server.pem
    dest: "{{ SERVER_KEY_LOCATION }}{{ item }}/"
  become: yes
  when: inventory_hostname != MASTER_NAME

- name: Delete master pem
  local_action:
    module: file
    path: /tmp/ssl_nodes/{{ MASTER_NAME }}/server.pem
    state: absent
  run_once: yes
