---
- block:
    - block:
      - name: Generate keys and certs dir
        file:
          path: /root/ssl/{{ item }}
          state: directory
          mode: '0750'

      - name: Transfer inventory_hostname csr to ca
        copy:
          src: /tmp/ssl_nodes/{{ item }}/server.csr
          dest: /root/ssl/{{ item }}/server.csr

      - name: Gen certificate
        openssl_certificate:
          path: /root/ssl/{{ item }}/server.crt
          csr_path: /root/ssl/{{ item }}/server.csr
          ownca_path: /root/ssl/server.crt
          ownca_privatekey_path: /root/ssl/ca.key
          provider: ownca

      - name: Fetch host certificate
        fetch:
          src: /root/ssl/{{ item }}/server.crt
          dest: /tmp/ssl_nodes/{{ item }}/
          flat: yes
         
      - name: Delete csr and cert from ca
        file:
          path: /root/ssl/{{ item }}
          state: absent
      delegate_to: "{{ CA_INV_NAME }}"
    
    - name: Transfer inventory_hostname cert to server
      copy:
        src: /tmp/ssl_nodes/{{ item }}/server.crt
        dest: "{{ SERVER_CERT_LOCATION }}{{ item }}/"

    - name: Delete csr's from master
      local_action:
        module: file
        path: /tmp/ssl_nodes/{{ item }}/server.csr
        state: absent
  become: yes
